\def\academixData{2024/10/19}
\def\academixVersion{v1.0}

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{academix/academix}[\academixData\space version \academixVersion\space APA Class]

\input{academix/class_options}
\input{academix/definitions}
\input{academix/line_spacing}
\input{academix/margins}
\input{academix/page_style}
\input{academix/page_numbering}
\input{academix/chapter}
\input{academix/appendix}
\input{academix/lists}
\input{academix/reference}
\input{academix/index}
\input{academix/pre_text}
\input{academix/commands}

\endinput
